### ISSUE TITLE
Backend functionality for storing user created scripts

### ISSUE THREAD

**Issue by jithinbp** [fossasia/pslab-remote#16]
@viveksb007 @asitava1998 @CloudyPadmal In the [last PR](https://github.com/fossasia/pslab-remote/pull/14) , I embedded ace.js text editor on a page that allowed users to write their own Python code.

Now the question is how to store these.
Should they go into a database along with the Primary key user-email and a unique id for searchability, 
or
Should they be stored as text files in a directory.

Which begs the larger question ... if users are allowed to upload experiment results/screenshots as the app evolves, where is such data typically stored?

**Comment by viveksb007** [comment]
We can create an API in backend to store data on database. Then we can send parameters like code, link for screenshot (after uploading it somewhere),etc. 
Android App, desktop app and remote app all can make an api call to save experiment. 
In android app user can't write and execute code at runtime yet. As far as storing is concerned we can store code both locally and can make a ```POST``` call to store code,etc in remote db.

**Comment by jithinbp** [comment]
okay. I'm going with the following
+ Store user code directly into the database
+ When we get to the point of screenshots and stuff, they can be uploaded to cloudinary or something, and the link will be stored in the database.
I've read that the heroku free plan has a 5 MB per database limit, so I'm only going to handle text entries.

**Comment by asitava1998** [comment]
@jithinbp I agree with the approach you mentioned. Typically, data which is unlikely to be modified like screenshots should not be stored in databases but in some file system.  If the code is being changed quite a few times, it is better to store in the database.
