### ISSUE TITLE
Apply consistent naming "remote lab"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-remote#36]
The name virtual lab is already use by another project. The question here is anyways, if virtual lab would be the correct name. The goal of the project is to enable citizen scientists and students access to lab equipment that is not "virtual" but actually physically exists. This lab equipment is stationed remotely from the user. Therefore "remote lab" or something similar is probably a more correct naming.

**Comment by jithinbp** [comment]
I agree 'virtual lab' is a misnomer and that 'remote lab' is more accurate, but the former is also the term used in a range of projects in various universities across the country with a similar aim which use proprietary software such as LabView. The 'remote access' feature is one part of the broader umbrella of 'virtual labs' . Here's the [doc released](http://mhrd.gov.in/sites/upload_files/mhrd/files/press-releases/Rel23022012.pdf) by the Ministry of Human Resource Development in case you're interested 

From a visibility point of view, 'virtual' may be better suited, and I'm sure that this platform will also include simulators and educational resources as it evolves, but for now I've renamed it to 'remote lab'
